config/routes.rb
Rails.application.routes.draw do

  get 'groups/new'

  get 'sessions/new'

  get 'users/new'

  resources :tracks
  resources :users
  resources :groups
  resources :group_messages, only: [:index, :new, :create, :destroy]
  resources :events, except: [:index]

  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  post 'delete_group_message' => 'group_messages#destroy'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'join_group' => 'groups#join'
  get 'leave_group' => 'groups#leave'
  get 'join_event' => 'events#join'
  get 'leave_event' => 'events#leave'
  delete 'logout'  => 'sessions#destroy'
  get 'search' => 'main_search#index'
  get 'messages' => 'users#messages'
  post 'create_track' => 'tracks#create'
  post 'get_track' => 'tracks#get'
<<<<<<< HEAD
=======
  get 'move_tracks' => 'tracks#move_to_backend'
>>>>>>> 184974e0449ca5a050addb821f7188b608a8c3aa

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>
<p>
	Ever wondered how to meet other wonderful bicyclists?<br/>
	Tindbike is your perfect opportunity to begin a new fullfilled life!
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Help</h1>
<p>Because this site is so awesome you ain't gonna need no help!</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to Tindbike</h1>

  <h2>
	  Thousands of bike enthusiasts are waiting for you.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" if !logged_in? %>
  <%= link_to "Browse groups", groups_path, class: "btn btn-lg btn-success" if logged_in? %>
</div>