config/routes.rb
Rails.application.routes.draw do

  get 'groups/new'

  get 'sessions/new'

  get 'users/new'

  resources :tracks
  resources :users
  resources :groups
  resources :group_messages, only: [:index, :new, :create, :destroy]
  resources :events, except: [:index]

  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  post 'delete_group_message' => 'group_messages#destroy'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'join_group' => 'groups#join'
  get 'leave_group' => 'groups#leave'
  get 'join_event' => 'events#join'
  get 'leave_event' => 'events#leave'
  delete 'logout'  => 'sessions#destroy'
  get 'search' => 'main_search#index'
  get 'messages' => 'users#messages'
  post 'create_track' => 'tracks#create'
  post 'get_track' => 'tracks#get'
<<<<<<< HEAD
=======
  get 'move_tracks' => 'tracks#move_to_backend'
>>>>>>> 184974e0449ca5a050addb821f7188b608a8c3aa

end

app/models/group.rb
class Group < ActiveRecord::Base
  include SearchCop

  mount_uploader :picture, PictureUploader
  
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :details, presence: true, length: { maximum: 250 }

  validate  :picture_size
  
  has_and_belongs_to_many :users
  has_many :group_messages, dependent: :destroy
  has_many :events, dependent: :destroy

  search_scope :search do
    attributes :name
  end

  def is_member?(user_id)
    users.where("id = ?", user_id).size > 0
  end


  private

  # Validates the size of an uploaded picture.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :logged_in_user
  before_action :set_group, only: [:show, :edit, :join, :leave, :update]
  
  def new
    @group = Group.new
  end

  def show
    @group_messages = @group.group_messages.paginate(page: params[:page])
  end

  def edit
  end

  def join
    UserMessageService.send_system_group_message(current_user.name +
      " ist der Gruppe " + @group.name +
      " beigetreten.", @group)
    current_user.groups << @group
    current_user.save
    flash[:success] = "You successfully joined #{@group.name}."
    redirect_to :back
  end

  def leave
    current_user.groups.delete(@group)
    UserMessageService.send_system_group_message(current_user.name +
      " ist aus der Gruppe " + @group.name +
      " ausgetreten.", @group)
    flash[:success] = "You successfully left #{@group.name}."
    redirect_to :back
  end

  def index
    @group_membership = User.group_membership(current_user)
    @groups = Group.all
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      @group.users << current_user
      @group.save
      flash[:success] = "Group #{@group.name} was successfully created."
      redirect_to @group
    else
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_group
    if params[:id]
      @group = Group.find(params[:id])
    end
    
    if params[:group_id]
      @group = Group.find(params[:group_id])
    end
  end

  def group_params
    params.require(:group).permit(:name, :details, :picture)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_events.erb
<div class="row">

  <h3>
    Events (<%= @group.events.size %>)
    <%= link_to "Create new Event", new_event_path(group_id: @group.id), class: "btn btn-primary" if @group.users.include? current_user %>
  </h3>

  <table class="table table-striped">

    <thead>
    <tr>
      <th class="col-md-1"></th> <!-- col for pictures -->
      <th class="col-md-2">Name</th>
      <th class="col-md-2">Details</th>
      <th class="col-md-2">Track</th>
      <th class="col-md-2">Action</th>
    </tr>
    </thead>

    <tbody>

    <% @group.events.each do |event| %>
        <tr>
          <td><%= thumbnail(event) %></td>
          <td><%= link_to event.name, event_path(id: event.id) %></td>
          <td><%= event.details %></td>
          <td><%= link_to event.track.to_s, track_path(track_id: event.track) %></td>
          <% unless event.is_member? current_user.id %>
              <td><%= link_to 'Join Event', join_event_path(event_id: event.id), class: "btn btn-success" %></td>
          <% else %>
              <td><%= link_to 'Leave Event', leave_event_path(event_id: event.id), class: "btn btn-warning" %></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>

  </table>
</div>

app/views/groups/_group_messages.erb
<h3>Posts (<%= @group.group_messages.count %>)
  <%= link_to "Create new Post", new_group_message_path(group_id: @group.id), class: "btn btn-primary" if @group.users.include? current_user %></h3>
<% if @group.group_messages.any? %>
  <ol class="group_messages">
    <%= render @group_messages %>
  </ol>
  <%= will_paginate @group_messages %>
<% end %>

app/views/groups/_members.erb
<div class="row">

  <h3>Members (<%= @group.users.size %>)</h3>

  <table class="table table-striped">

    <thead>
    <tr>
      <th class="col-md-1"></th> <!-- col for pictures -->
      <th class="col-md-2">Username</th>
      <th class="col-md-2">Name</th>
      <th class="col-md-2">Details</th>
    </tr>
    </thead>

    <tbody>

    <% @group.users.each do |user| %>
        <tr>
          <td><%= thumbnail(user) %></td>
          <td><%= link_to user.username, user_path(id: user.id) %></td>
          <td><%= "#{user.first_name} #{user.name}" %></td>
          <td><%= user.details %></td>
        </tr>
    <% end %>
    </tbody>

  </table>
</div>

app/views/groups/_show_groups.erb
<div class="row">
  <table class="table table-striped">

    <thead>
    <tr>
      <th class="col-md-1"></th>
      <!-- col for pictures -->
      <th class="col-md-2">Name</th>
      <th class="col-md-4">Description</th>
      <th class="col-md-1"></th>
    </tr>
    </thead>

    <tbody>
    <% @groups.each do |group| %>
        <tr>
          <td><%= thumbnail(group) %></td>
          <td><%= link_to group.name, group_path(id: group.id) %></td>
          <td><%= group.details %></td>
          <% unless group.is_member? current_user.id %>
              <td><%= link_to 'Join Group', join_group_path(group_id: group.id), class: "btn btn-success" %></td>
          <% else %>
              <td><%= link_to 'Leave Group', leave_group_path(group_id: group.id), class: "btn btn-warning" %></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>

  </table>
</div>

app/views/groups/index.html.erb
<br/>
<div class="row">
    <%= link_to "Create new Group", new_group_path, :class => "btn btn-primary pull-right col-lg-2" %>
</div>

<br/>

<%= render "show_groups"%>

app/views/groups/new.html.erb
<% provide(:title, 'Create new Group') %>
<h1>Create new Group</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@group) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
	  <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :Description %>
      <%= f.text_area :details, class: 'form-control', :rows => 10 %>

      <%= f.label :picture, "Picture"%>
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>

      <%= f.submit "Create new Group", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="row col-md-12">
  <div class="row col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title" style="font-size: 28px"><%= @group.name %></h3>
      </div>

      <div class="panel-body text-center">
        <%= thumbnail(@group) %>
      </div>

      <div class="panel-footer text-center">
        <% if @group.is_member? current_user.id %>
            <%= link_to 'Leave Group', leave_group_path(group_id: @group.id), class: "btn btn-warning" %>
        <% else %>
            <%= link_to 'Join Group', join_group_path(group_id: @group.id), class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">Description</div>
      <div class="panel-body">
        <%= @group.details %>
      </div>
    </div>
  </div>

</div>

<%= render "events" %>

<%= render "members" %>

<%= render partial: 'group_messages' %>