config/routes.rb
Rails.application.routes.draw do

  get 'groups/new'

  get 'sessions/new'

  get 'users/new'

  resources :tracks
  resources :users
  resources :groups
  resources :group_messages, only: [:index, :new, :create, :destroy]
  resources :events, except: [:index]

  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  post 'delete_group_message' => 'group_messages#destroy'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'join_group' => 'groups#join'
  get 'leave_group' => 'groups#leave'
  get 'join_event' => 'events#join'
  get 'leave_event' => 'events#leave'
  delete 'logout'  => 'sessions#destroy'
  get 'search' => 'main_search#index'
  get 'messages' => 'users#messages'
  post 'create_track' => 'tracks#create'
  post 'get_track' => 'tracks#get'
<<<<<<< HEAD
=======
  get 'move_tracks' => 'tracks#move_to_backend'
>>>>>>> 184974e0449ca5a050addb821f7188b608a8c3aa

end

app/models/user.rb
class User < ActiveRecord::Base
  include SearchCop

  attr_accessor :errors_backend

  after_initialize :init

  after_validation { self.errors.messages.delete(:password_digest) }

  mount_uploader :picture, PictureUploader

  before_save { self.email = email.downcase }
  validates :name, presence: true
  validates :email, presence: true
  validates :name,  presence: true, length: { maximum: 50 }
  ONLY_LETTERS_AND_DIGITS_REGEX = /\A[0-9a-zA-Z]*\z/
  validates :username, presence: true,
                       length: { maximum: 20 },
                       format: { with: ONLY_LETTERS_AND_DIGITS_REGEX,
                                 message: "only letters and digits allowed" },
                       uniqueness: { case_sensitive: false }
  validates :password_digest, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 8 }, :allow_blank => true
  validate  :picture_size
  has_secure_password

  search_scope :search do
    attributes :name, :first_name, :username
  end

  belongs_to :address
  has_and_belongs_to_many :groups
  has_and_belongs_to_many :events
  has_many :group_messages
  has_many :send_messages, :class_name => 'UserMessage', :foreign_key => 'sender_id'
  has_many :recieved_messages, :class_name => "UserMessage", :foreign_key => 'reciever_id'
  has_many :tracks

  def self.group_membership(user)
    user.groups.pluck(:id)
  end

  private

  def init
    @errors_backend = []
  end

  # Validates the size of an uploaded picture.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: [:new, :create]
  before_action :set_user, only: [:update, :show, :edit, :messages]

  CONNECTOR = ConnectorFactory.connection

  def show
    @group_membership = User.group_membership(current_user)
    @groups = @user.groups
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.validate and
       CONNECTOR.create_user(@user) and
        @user.save
      log_in @user
      flash[:success] = "Welcome to Tindbike!"
      redirect_to @user
    else
      flash[:danger] = @user.errors_backend.map{ |error| error[:text] }.join("</br>").html_safe
      render 'new'
    end
  end

  def edit
  end

  def messages
    @recieved_messages = @user.recieved_messages
    @send_messages = @user.send_messages
  end

  def update
    respond_to do |format|
      old_user = @user.dup
      @user.assign_attributes(user_params)
      if @user.validate and
          CONNECTOR.connection(old_user).update_user(old_user.username, old_user, @user) and
          @user.save
        format.html { redirect_to @user }
        flash[:success] = 'User was successfully updated.'
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    if params[:id]
      @user = User.find(params[:id])
    else
      @user = current_user
    end
  end



  def user_params
    params.require(:user).permit(:username, :name, :email, :password,
                                 :password_confirmation, :picture)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_for @user, :html => {:multipart => true} do |f| %>
	  
	  <%= render 'shared/error_messages', object: f.object %>
	  
	  <%= f.label :username %>
	  <%= f.text_field :username, class: 'form-control' %>
	  
	  <%= f.label :name %>
	  <%= f.text_field :name, class: 'form-control' %>

	  <%= f.label :email %>
	  <%= f.text_field :email, class: 'form-control' %>

	  <%= f.label :password %>
	  <%= f.password_field :password, class: 'form-control' %>

	  <%= f.label :password_confirmation, "Confirmation" %>
	  <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :picture, "Picture"%>
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>

	  <%= f.submit "Update my account", class: "btn btn-primary" %>
	<% end %>
  </div>
</div>

app/views/users/_messages.erb
<table class="table table-striped">

  <colgroup>
	<col span="1" style="width: 20%;">
	<col span="1" style="width: 30%;">
    <col span="1" style="width: 50%;">
  </colgroup>
  
  <thead>
    <tr>
      <th></th>
      <th>Sender</th>
      <th>Message</th>
    </tr>
  </thead>
  <tbody>
    <% messages.each do |message| %>
      <tr>
        <td><%= message.created_at.strftime("%x %H:%M:%S") %></td>
        <td><%= link_to message.sender.username, user_path(id: message.sender.id) %></td>
        <td><%= message.message %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_show_users.html.erb
<div class="row">
    <table class="table table-striped">

        <!-- <colgroup>
            <col span="1" style="width: 33%;">
            <col span="1" style="width: 33%;">
            <col span="1" style="width: 33%;">
        </colgroup> -->

      <thead>
      <tr>
        <th class="col-md-1"></th> <!-- col for pictures -->
        <th class="col-md-2">Username</th>
        <th class="col-md-2">First Name</th>
        <th class="col-md-2">Details</th>
      </tr>
      </thead>

      <tbody>

            <% @users.each do |user| %>
                <tr>
                    <td><%= image_tag user.picture.url if user.picture? %></td>
                    <td><%= link_to user.username, user_path(id: user.id) %></td>
                    <td><%= "#{user.first_name} #{user.name}" %></td>
                    <td><%= user.details %></td>
                </tr>
            <% end %>
        </tbody>

    </table>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/messages.html.erb
<h2 class="pull-left">Recieved</h2>
<%= render partial: 'messages', :locals => {:messages => @recieved_messages} %>

<h2 class="pull-left">Sent</h2>
<%= render partial: 'messages', :locals => {:messages => @send_messages}%>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			
			<%= render 'shared/error_messages', object: f.object %>
			
			<%= f.label :username %>
			<%= f.text_field :username, class: 'form-control' %>
			
			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.text_field :email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "Create my account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="row col-md-12">
  <div class="row col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title" style="font-size: 28px"><%= @user.name %></h3>
      </div>

      <div class="panel-body text-center">
        <%= thumbnail(@user) %>

        <% if current_user?(@user) %>
            <br/><br/>
            <%= link_to messages_path, :class => 'btn btn-default' do %>
                Inbox <span class="badge"><%= @user.recieved_messages.count%></span>
            <% end %>
            <br/><br/>

            <p><%= link_to "Edit Profile", edit_user_path, class: "btn btn-default" %></p>
        <% end %>

      </div>
    </div>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">Description</div>
      <div class="panel-body">
        <%= @user.details %>
      </div>
    </div>
  </div>
  <div>
    <%= render partial: 'map'%>
  </div>
</div>



</div>

<script type="text/javascript">
    $('#user_picture').bind('change', function () {
        var size_in_megabytes = this.files[0].size / 1024 / 1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a smaller file.');
        }
    });
</script>