config/routes.rb
Rails.application.routes.draw do

  get 'groups/new'

  get 'sessions/new'

  get 'users/new'

  resources :tracks
  resources :users
  resources :groups
  resources :group_messages, only: [:index, :new, :create, :destroy]
  resources :events, except: [:index]

  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  post 'delete_group_message' => 'group_messages#destroy'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'join_group' => 'groups#join'
  get 'leave_group' => 'groups#leave'
  get 'join_event' => 'events#join'
  get 'leave_event' => 'events#leave'
  delete 'logout'  => 'sessions#destroy'
  get 'search' => 'main_search#index'
  get 'messages' => 'users#messages'
  post 'create_track' => 'tracks#create'
  post 'get_track' => 'tracks#get'
<<<<<<< HEAD
=======
  get 'move_tracks' => 'tracks#move_to_backend'
>>>>>>> 184974e0449ca5a050addb821f7188b608a8c3aa

end

app/views/layouts/_google_analytics.html.erb
<% if Rails.env.production? %>
  <script type="text/javascript">
   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
   })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

   ga('create', 'UA-57790834-2', 'auto');
   ga('send', 'pageview');

  </script>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Tindbike", root_path, id: "logo" %>
    <% if logged_in? %>
      <%= form_tag(search_path, method: :get) do %>
        <%= search_field_tag :search_text, params[:search_text], :class => "search", :maxlength=>"75", :placeholder => "Search for users and groups..." %>
      <% end %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav pull-right">
		<li><%= link_to "Home",   root_path %></li>
		<li><%= link_to "Help",   help_path %></li>
		<li><%= link_to "About",  about_path %></li>
		<% if logged_in? %>
          <li><%= link_to "Groups", groups_path %></li>
          <li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">
			  Account <b class="caret"></b>
			</a>
			<ul class="dropdown-menu">
			  <li><%= link_to "Profile", current_user %></li>
			  <li><%= link_to "Messages", messages_path %></li>
			  <li class="divider"></li>
			  <li>
				<%= link_to "Log out", logout_path, method: "delete" %>
			  </li>
			</ul>
		  </li>
		<% else %>
		  <li><%= link_to "Log in", login_path %></li>
		<% end %>
	  </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Tindbike</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <%= render 'layouts/google_analytics' %>
</head>
<body>
	<%= render 'layouts/header' %>
    <div class="container">
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>"><%= message %></div>
		<% end %>
 		<%= yield %>
    </div>
	<%= debug(params) if Rails.env.development? %>
</body>
</html>